-- MySQL Script generated by MySQL Workbench
-- Mon Mar  6 15:00:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema partyst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema partyst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `partyst` DEFAULT CHARACTER SET utf8 ;
USE `partyst` ;

-- -----------------------------------------------------
-- Table `partyst`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partyst`.`place` (
  `idPlace` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `partyst`.`party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partyst`.`party` (
  `idParty` INT NOT NULL AUTO_INCREMENT,
  `idPlace` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NULL,
  `date` VARCHAR(45) NOT NULL,
  `hour` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `ticket` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParty`, `idPlace`),
  INDEX `fk_party_places_idx` (`idPlace` ASC),
  CONSTRAINT `fk_party_places`
    FOREIGN KEY (`idPlace`)
    REFERENCES `partyst`.`place` (`idPlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
